#!/bin/sh -e

BASEDIR=$(dirname $0)

. "$BASEDIR/libshell/shell-getopt"
. "$BASEDIR/libshell/shell-error"

usage() {
  cat << EOF
Usage:  do-backup -f FILE -d DESTDIR [OPTIONS]

  Switches:
    -f, --file FILE 		Files/dirs to backup should be listed in FILE one
                                per line.
        Lines starting with 'exclude:' specify locations to exclude from backup.
        Lines starting with 'pre:' and 'post:' specify shell commands to run
          before and after backup running.
        Lines starting with 'compress:' specify which kind of compression to
          apply to archive. Possible values: tar, gzip. Default: gzip

        Several -f switches can be specified in which case several archives
        will be created.
    -l, --list DIR		search *.list files from specified dir and pass them
                                  as params to -f key
    -d, --destdir DESTDIR	a target dir to put archive into
    -e, --encrypt KEY		encrypt backup with specified GPG key
    -u, --upload BUCKET		upload archive to S3 bucket
    -s, --secret SECRET         a path to .awssecret secrets file
    -r, --rotate NUMBER		keep NUMBER of last archives
                                This applies both to local storage and to S3
    --lr, --local-rotate NUMBER	The same as -r but for local archives only
    --rr, --remote-rotate NUMBER	The same as -r but for remote archives only
      This two keys, --lr and --rr override -r
EOF
  exit 1
}

#  rotator() - Makes actual rotation
#  Params:
#    LIST_COMMAND should produce a list of backups -- one per line
#    RM_COMMAND should remove a backup supplied as a parameter.
#    !!! NO space added after the command to let it construct paths
#        therefore you should specify 'rm -f ' instead of 'rm -f' for that
rotator() {
  [ -z "$3" ] && fatal "Usage: rotator 'LIST COMMAND' 'RM COMMAND' NUMBER"

  local LISTC RMC ROTATE
  LISTC="$1"
  RMC="$2"
  ROTATE="$3"

  CNT=$( eval "$LISTC" | wc -l)
  if [ $CNT -gt $ROTATE ]; then
    ROT=$(($CNT - $ROTATE))
    for file in $( eval "$LISTC" | sort | head -n $ROT ); do
      eval "${RMC}${file}"
    done
  fi
}

run_hooks() {
  local OLD_IFS

  OLD_IFS=$IFS
  IFS="\n"
  echo "$@" | while read command; do
    eval "$command" 1>&2
  done
  IFS=$OLD_IFS
}

BACKUPLIST=''

while getoptex "d: destdir: f: file: e: encrypt: u: upload: s: secret: r: rotate: lr: local-rotate: rr: remote-rotate: l: list:" "$@"; do
  case $OPTOPT in
    f|file)    BACKUPLIST="$BACKUPLIST $OPTARG" ;;
    d|destdir) DESTDIR="$OPTARG" ;;
    e|encrypt) ENCRYPT="$OPTARG" ;;
    u|upload)  UPLOAD="$OPTARG" ;;
    s|secret)  SECRET="--secrets-file=$OPTARG" ;;
    r|rotate)
      ROTATE="$OPTARG"
      [ "$ROTATE" -gt 0 ] || fatal "--rotate requires positive integer as a param"
      ;;
    lr|local-rotate)
      LROTATE="$OPTARG"
      [ "$LROTATE" -gt 0 ] || fatal "--local-rotate requires positive integer as a param"
      ;;
    rr|remote-rotate)
      RROTATE="$OPTARG"
      [ "$RROTATE" -gt 0 ] || fatal "--remote-rotate requires positive integer as a param"
      ;;
    l|list)
      if [ -n "$BACKUPLIST" ]; then
        fail "--list requires no other sources (-l, -f) be specified before it"
      else
        BACKUPLIST=$(ls "$OPTARG"/*.list)
        STRIPNAMES=1
      fi
  esac
done

[ -z "$LROTATE" ] && LROTATE="$ROTATE"
[ -z "$RROTATE" ] && RROTATE="$ROTATE"

shift $(($OPTIND-1))
set -- $@ ${OPTUKN-}

for arg in $@; do
  fatal "Unknown option found: $arg"
done

[ -z "$BACKUPLIST" ] && usage
[ -z "$DESTDIR" ] && usage

[ -d "$DESTDIR" -a -w "$DESTDIR" ] || fatal "Target directory $DESTDIR not found or not accessible"

for list in $BACKUPLIST; do
  [ -r "$list" ] || fatal "File $list is not existant or is unreadable"
done

SUFFIX=$(date +%F-%T | sed 's,:,.,g')

for file in $BACKUPLIST; do
  LISTNAME=$(basename $file)
  [ -n "$STRIPNAMES" ] && LISTNAME=$(echo "$LISTNAME" | sed 's,.list,,') 
  AEXT='tgz'
  COMPRESS='-z'
  BACKUP_LIST=''
  EXCLUDE_LIST=''

  while read line; do
    case "$line" in
      \#*) ;;	# a comment
      exclude:*)
         EXCLUDE_LIST="$EXCLUDE_LIST --exclude=$(echo $line | sed 's,^exclude:[[:blank:]]*,,')" ;;
      pre:*)
         PRE="$PRE\n$(echo "$line" | sed 's,^pre:[[:blank:]]*,,')" ;;
      post:*)
         POST="$POST\n$(echo "$line" | sed 's,^post:[[:blank:]]*,,')" ;;
      compress:*)
        line="$( echo "$line" | sed 's,^compress:[[:blank:]]*,,')"
        case "$line" in
          none|tar)
            AEXT='tar'
            COMPRESS='' ;;
          gz|gzip)
            AEXT='tgz'
            COMPRESS='-z' ;;
          *)  fatal "Unknown compression method: '$line'" ;;
        esac ;;
      *) BACKUP_LIST="$BACKUP_LIST $line" ;;
    esac
  done < "$file"

  [ -n "$ENCRYPT" ] && EXT='gpg' || EXT="$AEXT"
  ARCHIVE="$DESTDIR/$LISTNAME-$SUFFIX.$AEXT"
  MATCH="$LISTNAME-*.$EXT"
  S3MATCH="$LISTNAME-.*\.$EXT"

  run_hooks "$PRE"

  tar -C "$DESTDIR" $COMPRESS -cf "$ARCHIVE" $BACKUP_LIST $EXCLUDE_LIST
  if [ -n "$ENCRYPT" ]; then
    gpg -r "$ENCRYPT" -e "$ARCHIVE" 
    ARCHIVE="$ARCHIVE.gpg"
  fi
  [ -n "$UPLOAD" ] && aws --silent --simple "$SECRET" put "$UPLOAD/$(basename "$ARCHIVE")" "$ARCHIVE"
  echo "$ARCHIVE"

  run_hooks "$POST"

  if [ -n "$LROTATE" -o -n "$RROTATE" ]; then
    if ( echo "$file" | egrep '^(/proc|/dev)' ); then
      echo WARNING: Input file is special device or descriptor -- rotation disabled > /dev/stderr
    else
      if [ -n "$LROTATE" ]; then
        rotator "find \"$DESTDIR\" -name \"$MATCH\"" 'rm -f ' "$LROTATE"
      fi
      if [ -n "$RROTATE" -a -n "$UPLOAD" ]; then
        BUCKET=$(echo "$UPLOAD" | sed 's,/.*,,')
        if echo "$UPLOAD" | grep -q '/'; then
          PREFIX=$(echo "$UPLOAD" | sed 's,[^/]*/,,')
          PREFIX="$PREFIX/" ||:
        fi
        S3MATCH="^${PREFIX}${S3MATCH}"
        rotator "aws --silent --simple \"$SECRET\" ls \"$UPLOAD\" | awk '{print \$4}' | grep \"$S3MATCH\"" \
                "aws --silent --simple \"$SECRET\" rm \"$BUCKET\"/" \
                "$RROTATE"
      fi
    fi
  fi
done
