#!/bin/sh -e

. ./libshell/shell-getopt
. ./libshell/shell-error

usage() {
  cat << EOF
Usage:  do-backup -f FILE -d DESTDIR

  Switches:
    -f  Files/dirs to backup should be listed in FILE one per line.
        Lines starting with *exclude* specify locations to exclude from backup
        Several -f switches can be specified in which case several archives
        will be created.
    -d, --destdir DESTDIR	a target dir to put archive into
EOF
  exit 1
}

BACKUPLIST=""
while getoptex "d: destdir: f: file: e: encrypt:" "$@"; do
  case $OPTOPT in
    f|file)    BACKUPLIST="$BACKUPLIST $OPTARG" ;;
    d|destdir) DESTDIR="$OPTARG" ;;
    e|encrypt) ENCRYPT="$OPTARG" ;;
  esac
done

shift $(($OPTIND-1))
set -- $@ ${OPTUKN-}

for arg in $@; do
  fatal "Unknown option found: $arg"
done

[ -z "$BACKUPLIST" ] && usage
[ -z "$DESTDIR" ] && usage

for list in $BACKUPLIST; do
  [ -r "$list" ] || fatal "File $list is not existant or unreadable"
done

SUFFIX=$(date +%F-%T | sed 's,:,.,g')

for file in $BACKUPLIST; do
  LISTNAME=$(basename $file)
  ARCHIVE="$DESTDIR/$LISTNAME-$SUFFIX.tgz"
  BACKUP_LIST=$( cat $file | grep -v '*exclude*' )
  EXCLUDE=$(cat $file | grep '*exclude*' | sed 's,^[[:blank:]]\*exclude\*[[:blank:]]*,,')

  EXCLUDE_LIST=''
  for pattern in $EXCLUDE; do
    EXCLUDE_LIST="$EXCLUDE_LIST --exclude=$pattern"
  done 

  tar -C "$DESTDIR" -zcf "$ARCHIVE" $BACKUP_LIST $EXCLUDE_LIST
  if [ -n "$ENCRYPT" ]; then
    gpg -r "$ENCRYPT" -e "$ARCHIVE" 
  fi
done
